### ISSUE TITLE
Training model and documentation

### ISSUE THREAD

**Issue by deepseek** [SURFZJY/EAST-caffe#1]
@SURFZJY What is the code status?
will you add documentation and pre-trained models?

**Comment by SURFZJY** [comment]
The code can be run (both the train.py and the demo.py) if you have configured the caffe enviornment.  You can change the Relu6 layer to Relu if you do not compile the relu6 support. We will provide vgg16 and some other efficient modelsl in the future. Some demos or the pretrianed models will be added in the future too.

**Comment by SURFZJY** [comment]
The project has been cleared up, and the pretained model has been provided.

**Comment by deepseek** [comment]
@SURFZJY Thanks for your hard work, your amazing.

Installing caffe have been a nightmare to me, I still can't get caffe to compile.....
hmmm.....
